version = 0.1
[default.deploy.parameters]
stack_name = "serverless-rag"
resolve_s3 = true
s3_prefix = "serverless-rag"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["DocumentProcessorFunction=894644507764.dkr.ecr.us-east-1.amazonaws.com/serverlessragd0266bbc/documentprocessorfunctionb22e788brepo"]