version = 0.1
[default.deploy.parameters]
stack_name = "serverless-rag"
resolve_s3 = true
s3_prefix = "serverless-rag"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["DocumentProcessorFunction=894644507764.dkr.ecr.us-east-1.amazonaws.com/serverlessragd0266bbc/documentprocessorfunctionb22e788brepo", "QueryFunction=894644507764.dkr.ecr.us-east-1.amazonaws.com/serverlessragd0266bbc/queryfunction87654789repo"]
